services:
  - type: web
    name: fayda-id-bot
    env: python
    region: oregon  # or frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python keep_alive.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    plan: free
    pythonVersion: "3.11.0"  # ðŸ‘ˆ THIS FORCES PYTHON 3.11
