services:
  - type: web
    name: fayda-id-bot
    env: python
    region: oregon
    buildCommand: |
      apt-get update && apt-get install -y libzbar0
      pip install -r requirements.txt
    startCommand: python keep_alive.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    plan: free
