services:
  - type: web
    name: fayda-id-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python keep_alive.py
    envVars:
      - key: BOT_TOKEN
        sync: false
    plan: free